In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

In [3]:
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [9]:
arr2 = np.array([1,2,3,4,5])
x2 = arr2.view()
x2[0] = 31

In [10]:
print(arr2)
print(x2)

[31  2  3  4  5]
[31  2  3  4  5]


In [11]:
arrr = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
a = arrr.copy()
b = arrr.view()

In [12]:
print(a.base)
print(b.base)

None
[11 22 33 44 55 66 77 88 99]


## Array Slicing

In [15]:
print(arrr[3:5])

[44 55]
